import { Inter } from "next/font/google";
import "@/styles/globals.css";
import AuthProvider from "@/service/authentication/AuthProvider";
import NotifProvider from "@/service/notification/NotifProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard Notification",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <AuthProvider>
          <NotifProvider>{children}</NotifProvider>
        </AuthProvider>
      </body>
    </html>
  );
}